Feat: added fixes and updated workflows
2501-ai/cli pull request #35
Opened 2024-09-27 16:14 UTC by shide1989

2024-09-28 01:30 UTC, alxpereira requested changes

2024-09-28 01:30 UTC, alxpereira commented on src/helpers/streams.ts
> +          // The default message is too verbose..
why keeping that ?

2024-10-04 08:29 UTC, shide1989 commented on src/helpers/streams.ts
> +          // The default message is too verbose..
for knowledge. Some models (meta) send us more messages. This might be too verbose

2024-10-04 08:30 UTC, shide1989 commented on src/helpers/streams.ts
> +          // The default message is too verbose..
I can remove the code if you want

2024-10-04 15:59 UTC, alxpereira approved these changes

2024-10-04 16:00 UTC, merged