flush only the current workspace by default, --all for all
2501-ai/cli pull request #88
Opened 2024-12-06 02:30 UTC by alxpereira

# 🚀 Pull Request Overview

### What does this PR do? 🤔

allowing user to flush only the current workspace by default, and using --all if needed all flush
avoiding loss of progression in the other workspaces

## 💻 Changes Summary

- ✅ **Change 1**: Change in the flush method

2024-12-06 08:07 UTC, shide1989 reviewed
aside from maybe updating the JSDoc lgtm

2024-12-06 08:07 UTC, shide1989 commented on src/utils/conf.ts
>   * Clears all agents from the configuration.
maybe update the JSdoc ?

2024-12-06 08:12 UTC, BonnardValentin approved these changes

2024-12-09 07:44 UTC, maxbeworks requested changes

2024-12-09 07:44 UTC, maxbeworks commented on src/utils/conf.ts
> +    console.log('config, all:', config);
remove console log

2024-12-10 09:07 UTC, BonnardValentin approved these changes

2024-12-12 03:41 UTC, maxbeworks approved these changes

2024-12-13 04:48 UTC, zhuk-aa commented on src/utils/conf.ts
>   * Clears all agents from the configuration.
fixed

2024-12-13 04:48 UTC, merged